import styles from '@/styles/Home.module.css'
import Head from 'next/head'

import { Filter } from '@/components/Filter'
import { Favorites } from '@/components/Favorites'
import { CharacterList } from '@/components/CharacterList'
import { Contact } from '@/components/Contact'


export default function Home() {
  return (
    <>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.logo} />
        <Filter />
        <CharacterList />
        <Favorites />
        <Contact />
      </main>
    </>
  )
}


