import styles from '@/styles/Home.module.css'
import Head from 'next/head'

import { CharacterList } from '@/components/CharacterList'
import { Favorites } from '@/components/Favorites'
import { Hero } from '@/components/Hero'
import {GetServerSideProps} from 'next'


export default function Home() {
  return (
    <>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Hero />
        <CharacterList />
        <Favorites />
      </main>
    </>
  )
}


export const getServerSideProps:GetServerSideProps = async ({ req, res }) =>{
  res.setHeader(
    'Cache-Control',
    'public, s-maxage=10, stale-while-revalidate=59'
  )

  return {
    props: {},
  }
}